const GRAVITY_INC = 'GRAVITY_INC';
const GRAVITY_DEC = 'GRAVITY_DEC';
const SHAPE_PER_SEC_INC = 'SHAPE_PER_SEC_INC';
const SHAPE_PER_SEC_DEC = 'SHAPE_PER_SEC_DEC';

const UPDATE_COUNTERS = 'UPDATE_COUNTERS';
const UPDATE_HEADERS = 'UPDATE_HEADERS';

const MAIN_INITED = 'MAIN_INITED';

const PIXI_TICK = 'PIXI_TICK';
const PIXI_ADD_SHAPE = 'PIXI_ADD_SHAPE';
const PIXI_ADD_SHAPE_TO_POINT = 'PIXI_ADD_SHAPE_TO_POINT';
const PIXI_STAGE_CLIKED = 'PIXI_STAGE_CLIKED';
const PIXI_SHAPE_CLIKED = 'PIXI_SHAPE_CLIKED';

export default {
  GRAVITY_INC,
  GRAVITY_DEC,
  SHAPE_PER_SEC_INC,
  SHAPE_PER_SEC_DEC,
  UPDATE_COUNTERS,
  UPDATE_HEADERS,
  MAIN_INITED,
  PIXI_TICK,
  PIXI_ADD_SHAPE,
  PIXI_ADD_SHAPE_TO_POINT,
  PIXI_STAGE_CLIKED,
  PIXI_SHAPE_CLIKED

}